In [1]:
import numpy as np

In [2]:
def verifyOutputInTraining(x, weight):
    y = np.dot(weight.T, x)
    y[y < 0] = -1
    y[y >= 0] = 1
    return np.array(y)


In [3]:
def targetOnOutput(y, weight):
    x = np.dot(weight, y)
    x[x <= 0] = -1
    x[x > 0] = 1
    return np.array(x)

In [6]:
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)
x3 = np.array([1, 1, -1, -1, 1, 1]).reshape(6, 1)
x4 = np.array([-1, -1, 1, 1, -1, -1]).reshape(6, 1)

y1 = np.array([1, 1, 1]).reshape(3, 1)
y2 = np.array([-1, -1, -1]).reshape(3, 1)
y3 = np.array([1, -1, 1]).reshape(3, 1)
y4 = np.array([-1, 1, -1]).reshape(3, 1)

In [7]:
# Calculate weight Matrix: W
inputSet = np.concatenate((x1, x2, x3, x4), axis = 1)
targetSet = np.concatenate((y1.T, y2.T, y3.T, y4.T), axis = 0)
weight = np.dot(inputSet, targetSet)

In [8]:
print(f"Weight matrix: {weight}")

Weight matrix: [[4 0 4]
 [4 0 4]
 [0 4 0]
 [0 4 0]
 [4 0 4]
 [4 0 4]]


In [9]:
print("Testing for input patterns: Set A")


print(f"Output of input pattern 1: {verifyOutputInTraining(x1, weight)}")

print(f"Output of input pattern 2: {verifyOutputInTraining(x2, weight)}")

print(f"Output of input pattern 3: {verifyOutputInTraining(x3, weight)}")

print(f"Output of input pattern 4: {verifyOutputInTraining(x4, weight)}")


Testing for input patterns: Set A
Output of input pattern 1: [[1]
 [1]
 [1]]
Output of input pattern 2: [[-1]
 [-1]
 [-1]]
Output of input pattern 3: [[ 1]
 [-1]
 [ 1]]
Output of input pattern 4: [[-1]
 [ 1]
 [-1]]


In [10]:
print(f"Testing for target patterns: Set B")

print(f"Output of target pattern 1: {targetOnOutput(y1, weight)}")

print(f"Output of target pattern 2: {targetOnOutput(y2, weight)}")

print(f"Output of target pattern 3: {targetOnOutput(y3, weight)}")

print(f"Output of target pattern 4: {targetOnOutput(y4, weight)}")


Testing for target patterns: Set B
Output of target pattern 1: [[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
Output of target pattern 2: [[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]
Output of target pattern 3: [[ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]]
Output of target pattern 4: [[-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [-1]]
