# Assignment 2

Titanic Dataset analysis

In [27]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [28]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [29]:
%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
import pandas as pd
import matplotlib as mlt

In [13]:
df = pd.read_csv('./train.csv', delimiter=',')

In [14]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [15]:
df.shape

(891, 12)

In [16]:
# Dependent Variable (target)
target = df['Survived']

In [17]:
# Independent Variable (data)
df.drop('Survived', axis=1, inplace=True)
data = df

In [18]:
print(data.columns)
print(target.name)

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Survived


In [19]:
# To check which data has NaN values
data.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [20]:
# Age has NaN values

# Filling with mean
x = data.copy()
x.Age.fillna(x.Age.mean(), inplace=True)
# Filling with median✨
y = data.copy()
y.Age.fillna(y.Age.median(), inplace=True)
# Filling with mode
z = data.copy()
z.Age.fillna(z.Age.mode(), inplace=True)

In [21]:
x.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.836071   13.002015    1.102743    0.806057   49.693429
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    2.000000   22.000000    0.000000    0.000000    7.910400
50%     446.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%     668.500000    3.000000   35.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [22]:
y.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642   29.361582    0.523008    0.381594   32.204208
std     257.353842    0.836071   13.019697    1.102743    0.806057   49.693429
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    2.000000   22.000000    0.000000    0.000000    7.910400
50%     446.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    3.000000   35.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [23]:
z.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [25]:
%pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [30]:
#Fill the Categorical Variables with most recurring data / Mode of Columns
print("Total NaN values for Column Sex : " ,z.Sex.isnull().sum())
print("Total NaN values for Column Cabin : " ,z.Cabin.isnull().sum())
print("Total NaN values for Column Embarked : ",z.Embarked.isnull().sum())
z.Cabin.fillna(z.Cabin.mode().iloc[0],inplace=True)
z.Embarked.fillna(z.Embarked.mode().iloc[0],inplace=True)
print("Total NaN values for Column Cabin After Processing : " ,z.Cabin.isnull().sum())
print("Total NaN values for Column Embarked After Processing: ",z.Embarked.isnull().sum())

Total NaN values for Column Sex :  0
Total NaN values for Column Cabin :  687
Total NaN values for Column Embarked :  2
Total NaN values for Column Cabin After Processing :  0
Total NaN values for Column Embarked After Processing:  0


In [31]:
# One hot encoding of categorical Variables
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
# One Hot Encoding Sex Column
transformed = ohe.fit_transform(z[['Sex']])
print(transformed.toarray())

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]


In [39]:
print(ohe.categories_[0])

['female' 'male']


In [35]:
# Add the encoded array in the table
z[ohe.categories_[0]] = transformed.toarray()

In [36]:
# Now Drop the Sex Column from the table
z.drop("Sex",axis = 1,inplace=True)

In [40]:
# One Hot Encoding Cabin Column
transformed_Cabin = ohe.fit_transform(z[['Cabin']])

In [41]:
print(transformed_Cabin.toarray())
print(ohe.categories_)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[array(['A10', 'A14', 'A16', 'A19', 'A20', 'A23', 'A24', 'A26', 'A31',
       'A32', 'A34', 'A36', 'A5', 'A6', 'A7', 'B101', 'B102', 'B18',
       'B19', 'B20', 'B22', 'B28', 'B3', 'B30', 'B35', 'B37', 'B38',
       'B39', 'B4', 'B41', 'B42', 'B49', 'B5', 'B50', 'B51 B53 B55',
       'B57 B59 B63 B66', 'B58 B60', 'B69', 'B71', 'B73', 'B77', 'B78',
       'B79', 'B80', 'B82 B84', 'B86', 'B94', 'B96 B98', 'C101', 'C103',
       'C104', 'C106', 'C110', 'C111', 'C118', 'C123', 'C124', 'C125',
       'C126', 'C128', 'C148', 'C2', 'C22 C26', 'C23 C25 C27', 'C30',
       'C32', 'C45', 'C46', 'C47', 'C49', 'C50', 'C52', 'C54', 'C62 C64',
       'C65', 'C68', 'C7', 'C70', 'C78', 'C82', 'C83', 'C85', 'C86',
       'C87', 'C90', 'C91', 'C92', 'C93', 'C95', 'C99', 'D', 'D10 D12',
       'D11', 'D15', 'D17', 'D19', 'D20', 'D21', 'D26', 'D28', 'D

In [42]:
#Here the Number of Categories are very high and this can lead to very high memory consumption So we use label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

z['Cabin']= le.fit_transform(z['Cabin']) 
print(z.head())

   PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

    Age  SibSp  Parch            Ticket     Fare  Cabin Embarked  female  male  
0  22.0      1      0         A/5 21171   7.2500     47        S     0.0   1.0  
1  38.0      1      0          PC 17599  71.2833     81        C     1.0   0.0  
2  26.0      0      0  STON/O2. 3101282   7.9250     47        S     1.0   0.0  
3  35.0      1      0            113803  53.1000     55        S     1.0   0.0  
4  35.0      0      0            373450   8.0500     47        S     0.0   1.0  


In [43]:
transformed_Embarked = ohe.fit_transform(z[['Embarked']])
ohe.categories_
# As the Categories are less we use One Hot Encoding

[array(['C', 'Q', 'S'], dtype=object)]

In [44]:
# Adding the Above Categories in the Table
z[ohe.categories_[0]] = transformed_Embarked.toarray()
#Dropping the Embarked Category from the table
z.drop('Embarked',axis=1,inplace=True)

In [45]:
# Preprocessed Data for Errors and Categorical Variables
features = z.copy()
features.drop(['Name','Ticket'] , axis=1 , inplace=True)
features

PassengerId  Pclass   Age  SibSp  Parch     Fare  Cabin  female  male  \
0              1       3  22.0      1      0   7.2500     47     0.0   1.0   
1              2       1  38.0      1      0  71.2833     81     1.0   0.0   
2              3       3  26.0      0      0   7.9250     47     1.0   0.0   
3              4       1  35.0      1      0  53.1000     55     1.0   0.0   
4              5       3  35.0      0      0   8.0500     47     0.0   1.0   
..           ...     ...   ...    ...    ...      ...    ...     ...   ...   
886          887       2  27.0      0      0  13.0000     47     0.0   1.0   
887          888       1  19.0      0      0  30.0000     30     1.0   0.0   
888          889       3   NaN      1      2  23.4500     47     1.0   0.0   
889          890       1  26.0      0      0  30.0000     60     0.0   1.0   
890          891       3  32.0      0      0   7.7500     47     0.0   1.0   

       C    Q    S  
0    0.0  0.0  1.0  
1    1.0  0.0  0.0  
2    0.0  0.0  1.0  
3    0.0  0.0  1.0  
4    0.0  0.0  1.0  
..   ...  ...  ...  
886  0.0  0.0  1.0  
887  0.0  0.0  1.0  
888  0.0  0.0  1.0  
889  1.0  0.0  0.0  
890  0.0  1.0  0.0  

[891 rows x 12 columns]

In [46]:
# Perform Standardization without Sklearn Library
for i in features.columns :
    features[i] = (features[i] - features[i].mean()) / features[i].std()

In [47]:
features

PassengerId    Pclass       Age     SibSp     Parch      Fare     Cabin  \
0      -1.729137  0.826913 -0.530005  0.432550 -0.473408 -0.502163 -0.281723   
1      -1.725251 -1.565228  0.571430  0.432550 -0.473408  0.786404  1.160893   
2      -1.721365  0.826913 -0.254646 -0.474279 -0.473408 -0.488580 -0.281723   
3      -1.717480 -1.565228  0.364911  0.432550 -0.473408  0.420494  0.057716   
4      -1.713594  0.826913  0.364911 -0.474279 -0.473408 -0.486064 -0.281723   
..           ...       ...       ...       ...       ...       ...       ...   
886     1.713594 -0.369158 -0.185807 -0.474279 -0.473408 -0.386454 -0.281723   
887     1.717480 -1.565228 -0.736524 -0.474279 -0.473408 -0.044356 -1.003031   
888     1.721365  0.826913       NaN  0.432550  2.007806 -0.176164 -0.281723   
889     1.725251 -1.565228 -0.254646 -0.474279 -0.473408 -0.044356  0.269866   
890     1.729137  0.826913  0.158392 -0.474279 -0.473408 -0.492101 -0.281723   

       female      male         C         Q         S  
0   -0.737281  0.737281 -0.481772 -0.307390  0.615493  
1    1.354813 -1.354813  2.073341 -0.307390 -1.622891  
2    1.354813 -1.354813 -0.481772 -0.307390  0.615493  
3    1.354813 -1.354813 -0.481772 -0.307390  0.615493  
4   -0.737281  0.737281 -0.481772 -0.307390  0.615493  
..        ...       ...       ...       ...       ...  
886 -0.737281  0.737281 -0.481772 -0.307390  0.615493  
887  1.354813 -1.354813 -0.481772 -0.307390  0.615493  
888  1.354813 -1.354813 -0.481772 -0.307390  0.615493  
889 -0.737281  0.737281  2.073341 -0.307390 -1.622891  
890 -0.737281  0.737281 -0.481772  3.249548 -1.622891  

[891 rows x 12 columns]

In [48]:
features2 = z.copy()
features2.drop(['Name','Ticket'] , axis=1 , inplace=True)
features2

PassengerId  Pclass   Age  SibSp  Parch     Fare  Cabin  female  male  \
0              1       3  22.0      1      0   7.2500     47     0.0   1.0   
1              2       1  38.0      1      0  71.2833     81     1.0   0.0   
2              3       3  26.0      0      0   7.9250     47     1.0   0.0   
3              4       1  35.0      1      0  53.1000     55     1.0   0.0   
4              5       3  35.0      0      0   8.0500     47     0.0   1.0   
..           ...     ...   ...    ...    ...      ...    ...     ...   ...   
886          887       2  27.0      0      0  13.0000     47     0.0   1.0   
887          888       1  19.0      0      0  30.0000     30     1.0   0.0   
888          889       3   NaN      1      2  23.4500     47     1.0   0.0   
889          890       1  26.0      0      0  30.0000     60     0.0   1.0   
890          891       3  32.0      0      0   7.7500     47     0.0   1.0   

       C    Q    S  
0    0.0  0.0  1.0  
1    1.0  0.0  0.0  
2    0.0  0.0  1.0  
3    0.0  0.0  1.0  
4    0.0  0.0  1.0  
..   ...  ...  ...  
886  0.0  0.0  1.0  
887  0.0  0.0  1.0  
888  0.0  0.0  1.0  
889  1.0  0.0  0.0  
890  0.0  1.0  0.0  

[891 rows x 12 columns]

In [49]:
# Performing the Normalization Without Sklearn 
for column in features2.columns:
    features2[column] = (features2[column] - features2[column].min()) / (features2[column].max() - features2[column].min()) 

features2

PassengerId  Pclass       Age  SibSp     Parch      Fare     Cabin  \
0       0.000000     1.0  0.271174  0.125  0.000000  0.014151  0.321918   
1       0.001124     0.0  0.472229  0.125  0.000000  0.139136  0.554795   
2       0.002247     1.0  0.321438  0.000  0.000000  0.015469  0.321918   
3       0.003371     0.0  0.434531  0.125  0.000000  0.103644  0.376712   
4       0.004494     1.0  0.434531  0.000  0.000000  0.015713  0.321918   
..           ...     ...       ...    ...       ...       ...       ...   
886     0.995506     0.5  0.334004  0.000  0.000000  0.025374  0.321918   
887     0.996629     0.0  0.233476  0.000  0.000000  0.058556  0.205479   
888     0.997753     1.0       NaN  0.125  0.333333  0.045771  0.321918   
889     0.998876     0.0  0.321438  0.000  0.000000  0.058556  0.410959   
890     1.000000     1.0  0.396833  0.000  0.000000  0.015127  0.321918   

     female  male    C    Q    S  
0       0.0   1.0  0.0  0.0  1.0  
1       1.0   0.0  1.0  0.0  0.0  
2       1.0   0.0  0.0  0.0  1.0  
3       1.0   0.0  0.0  0.0  1.0  
4       0.0   1.0  0.0  0.0  1.0  
..      ...   ...  ...  ...  ...  
886     0.0   1.0  0.0  0.0  1.0  
887     1.0   0.0  0.0  0.0  1.0  
888     1.0   0.0  0.0  0.0  1.0  
889     0.0   1.0  1.0  0.0  0.0  
890     0.0   1.0  0.0  1.0  0.0  

[891 rows x 12 columns]

In [50]:
#Now to perform Standardization using the Sklearn Library
from sklearn.preprocessing import StandardScaler
features3 = z.copy()
features3.drop(['Name','Ticket'] , axis=1 , inplace=True)
scaler = StandardScaler()
features3 = scaler.fit_transform(features3)
features3

array([[-1.73010796,  0.82737724, -0.53037664, ..., -0.48204268,
        -0.30756234,  0.61583843],
       [-1.72622007, -1.56610693,  0.57183099, ...,  2.0745051 ,
        -0.30756234, -1.62380254],
       [-1.72233219,  0.82737724, -0.25482473, ..., -0.48204268,
        -0.30756234,  0.61583843],
       ...,
       [ 1.72233219,  0.82737724,         nan, ..., -0.48204268,
        -0.30756234,  0.61583843],
       [ 1.72622007, -1.56610693, -0.25482473, ...,  2.0745051 ,
        -0.30756234, -1.62380254],
       [ 1.73010796,  0.82737724,  0.15850313, ..., -0.48204268,
         3.25137334, -1.62380254]])

In [52]:
# Perform the Normalization using Sklearn library
features4 = z.copy()
features4.drop(['Name','Ticket'] , axis=1 , inplace=True)
from sklearn.preprocessing import normalize
features4 = normalize(features4)

ValueError: Input contains NaN.

In [53]:
pd.DataFrame(features4)

PassengerId  Pclass   Age  SibSp  Parch     Fare  Cabin  female  male  \
0              1       3  22.0      1      0   7.2500     47     0.0   1.0   
1              2       1  38.0      1      0  71.2833     81     1.0   0.0   
2              3       3  26.0      0      0   7.9250     47     1.0   0.0   
3              4       1  35.0      1      0  53.1000     55     1.0   0.0   
4              5       3  35.0      0      0   8.0500     47     0.0   1.0   
..           ...     ...   ...    ...    ...      ...    ...     ...   ...   
886          887       2  27.0      0      0  13.0000     47     0.0   1.0   
887          888       1  19.0      0      0  30.0000     30     1.0   0.0   
888          889       3   NaN      1      2  23.4500     47     1.0   0.0   
889          890       1  26.0      0      0  30.0000     60     0.0   1.0   
890          891       3  32.0      0      0   7.7500     47     0.0   1.0   

       C    Q    S  
0    0.0  0.0  1.0  
1    1.0  0.0  0.0  
2    0.0  0.0  1.0  
3    0.0  0.0  1.0  
4    0.0  0.0  1.0  
..   ...  ...  ...  
886  0.0  0.0  1.0  
887  0.0  0.0  1.0  
888  0.0  0.0  1.0  
889  1.0  0.0  0.0  
890  0.0  1.0  0.0  

[891 rows x 12 columns]